from .node1_discord_input import Node1_Discord_Input
from .node2_preprocessing import Node2_Preprocessing
from .node3_gemini import Node3_Gemini
from .node4_folder_management import Node4_Folder_Management
from .node5_file_creation import Node5_File_Creation
from .node6_content_writing import Node6_Content_Writing
from .node7_metadata_extraction import Node7_Metadata_Extraction
from .node8_discord_notification import Node8_Discord_Notification
