import re
import os
import datetime
from typing import Optional, List, Dict, Any
from google.oauth2 import service_account
from googleapiclient.discovery import build

def format_file_name(content: str) -> str:
    """
    Formats the file name based on the first line of content.

    Args:
        content (str): The markdown content generated by Gemini.

    Returns:
        str: A clean file name ending in .md.
    """
    if not content:
        return "Untitled.md"
        
    # Get first line
    lines = content.strip().split('\n')
    first_line = lines[0].strip() if lines else "Untitled"
    
    # Remove markdown headers (#) and clean invalid characters
    clean_name = first_line.replace('#', '').strip()
    
    # Replace invalid file system characters with underscore or empty
    # Windows/Linux forbidden chars: < > : " / \ | ? *
    clean_name = re.sub(r'[<>:"/\\|?*]', '', clean_name)
    
    # Limit length to avoid too long filenames (e.g. 100 chars)
    clean_name = clean_name[:100].strip()
    
    if not clean_name:
        clean_name = "Untitled"
        
    return f"{clean_name}.md"

def get_drive_service():
    """
    Authenticates with Google Drive API using OAuth 2.0 (preferred) or service account credentials.
    """
    SCOPES = ['https://www.googleapis.com/auth/drive']
    
    # 1. Try OAuth 2.0 (Refresh Token) - Required for Personal Accounts
    refresh_token = os.getenv('GOOGLE_REFRESH_TOKEN')
    if refresh_token:
        try:
            from google.oauth2.credentials import Credentials
            creds = Credentials(
                None, # No access token initially
                refresh_token=refresh_token,
                token_uri="https://oauth2.googleapis.com/token",
                client_id=os.getenv('GOOGLE_CLIENT_ID'),
                client_secret=os.getenv('GOOGLE_CLIENT_SECRET'),
                scopes=SCOPES
            )
            service = build('drive', 'v3', credentials=creds)
            return service
        except Exception as e:
            print(f"Error authenticating with OAuth 2.0: {e}")
            # Fallback to Service Account if OAuth fails? Or just return None.
    
    # 2. Fallback to Service Account
    creds_file = os.getenv('GOOGLE_SERVICE_ACCOUNT_FILE')
    
    if creds_file and os.path.exists(creds_file):
        try:
            creds = service_account.Credentials.from_service_account_file(
                creds_file, scopes=SCOPES)
            service = build('drive', 'v3', credentials=creds)
            return service
        except Exception as e:
            print(f"Error authenticating with Service Account: {e}")
            return None
            
    print("No valid authentication credentials found (OAuth or Service Account).")
    return None

def format_date_folder(date_str: str) -> str:
    """
    Formats date string into folder name (YYYY).
    Example: '2025-12-17T12:34:59+00:00' -> '2025'
    """
    try:
        # Simple parsing for ISO format, taking first 4 chars
        if date_str and len(date_str) >= 4:
            return date_str[:4]
    except Exception:
        pass
    return str(datetime.datetime.now().year)

def get_current_timestamp() -> str:
    """Returns current timestamp in ISO format."""
    return datetime.datetime.now().isoformat()

def filter_recent_items(items: List[Dict[str, Any]], hours: int = 0, minutes: int = 0) -> List[Dict[str, Any]]:
    """
    Filters items based on timestamp (not strictly needed for Node 8 as it processes all items from current run).
    Keeping implementation for compatibility.
    """
    return items
